### ISSUE TITLE
Mirroring by BCD path doesn't work for API mixins

### ISSUE THREAD

**Issue by foolip** [mdn/browser-compat-data#11483]
Try this:
> npm run mirror -- -m always samsunginternet_android api.Document.fullscreenElement

It will fail like this:
```
/Users/foolip/mdn/browser-compat-data/scripts/mirror.js:627
    if (data[rootPath].constructor == Object || Array.isArray(data[rootPath])) {
                       ^

TypeError: Cannot read property 'constructor' of undefined
    at setFeature (/Users/foolip/mdn/browser-compat-data/scripts/mirror.js:627:24)
    at setFeature (/Users/foolip/mdn/browser-compat-data/scripts/mirror.js:619:25)
    at setFeature (/Users/foolip/mdn/browser-compat-data/scripts/mirror.js:619:25)
    at mirrorDataByFeature (/Users/foolip/mdn/browser-compat-data/scripts/mirror.js:731:17)
    at mirrorData (/Users/foolip/mdn/browser-compat-data/scripts/mirror.js:764:5)
    at Object.<anonymous> (/Users/foolip/mdn/browser-compat-data/scripts/mirror.js:789:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

Mirroring by file name by contrast does work:
> npm run mirror -- -m always samsunginternet_android api/_mixins/DocumentOrShadowRoot__Document.json

@Elchi3 I'm guessing that this broke with the introduction of the api/_mixins/ direcrtory. Can you tell what's gone wrong here?

**Comment by Elchi3** [comment]
Maybe this is hitting https://github.com/mdn/browser-compat-data/issues/6585?

The mirroring script sees `api.Element.ariaAtomic` and makes the assumption that the dots map to file paths but here it is `api/_mixins/ARIAMixin__Element.json` and not `api/Element.json`.

**Comment by foolip** [comment]
Having that infrastructure in place would make it easier to solve this, yes. It's also possible to brute force it by just parsing all files and checking if the BCD path can be found in the resulting object.

**Comment by foolip** [comment]
Closing this, `npm run mirror -- -m always samsunginternet_android api/_mixins/DocumentOrShadowRoot__Document.json` works now.
