### ISSUE TITLE
<framework> - <no data>

### ISSUE THREAD

**Issue by Antny3360** [mdn/browser-compat-data#12217]
#### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?
framework-2f612445bd50b211f15a.js:1 DOMException: Failed to execute 'sendBeacon' on 'Navigator': sendBeacon() with a Blob whose type is not any of the CORS-safelisted values for the Content-Type request header is disabled temporarily. See http://crbug.com/490015 for details.
    at A (https://docs.github.com/_next/static/chunks/pages/_app-6dad4b8429480d2cb5ca.js:1:62178)
    at https://docs.github.com/_next/static/chunks/pages/_app-6dad4b8429480d2cb5ca.js:1:63452
    at j (https://docs.github.com/_next/static/chunks/pages/_app-6dad4b8429480d2cb5ca.js:1:63544)
    at https://docs.github.com/_next/static/chunks/pages/_app-6dad4b8429480d2cb5ca.js:1:68062
    at Ii (https://docs.github.com/_next/static/chunks/framework-2f612445bd50b211f15a.js:1:105601)
    at t.unstable_runWithPriority (https://docs.github.com/_next/static/chunks/framework-2f612445bd50b211f15a.js:1:130400)
    at Wl (https://docs.github.com/_next/static/chunks/framework-2f612445bd50b211f15a.js:1:45772)
    at Oi (https://docs.github.com/_next/static/chunks/framework-2f612445bd50b211f15a.js:1:105062)
    at https://docs.github.com/_next/static/chunks/framework-2f612445bd50b211f15a.js:1:104973
    at D (https://docs.github.com/_next/static/chunks/framework-2f612445bd50b211f15a.js:1:129459)
uu @ framework-2f612445bd50b211f15a.js:1
main-53e4c75c03e21105f4ea.js:1 DOMException: Failed to execute 'sendBeacon' on 'Navigator': sendBeacon() with a Blob whose type is not any of the CORS-safelisted values for the Content-Type request header is disabled temporarily. See http://crbug.com/490015 for details.
    at A (https://docs.github.com/_next/static/chunks/pages/_app-6dad4b8429480d2cb5ca.js:1:62178)
    at https://docs.github.com/_next/static/chunks/pages/_app-6dad4b8429480d2cb5ca.js:1:63452
    at j (https://docs.github.com/_next/static/chunks/pages/_app-6dad4b8429480d2cb5ca.js:1:63544)
    at https://docs.github.com/_next/static/chunks/pages/_app-6dad4b8429480d2cb5ca.js:1:68062
    at Ii (https://docs.github.com/_next/static/chunks/framework-2f612445bd50b211f15a.js:1:105601)
    at t.unstable_runWithPriority (https://docs.github.com/_next/static/chunks/framework-2f612445bd50b211f15a.js:1:130400)
    at Wl (https://docs.github.com/_next/static/chunks/framework-2f612445bd50b211f15a.js:1:45772)
    at Oi (https://docs.github.com/_next/static/chunks/framework-2f612445bd50b211f15a.js:1:105062)
    at https://docs.github.com/_next/static/chunks/framework-2f612445bd50b211f15a.js:1:104973
    at D (https://docs.github.com/_next/static/chunks/framework-2f612445bd50b211f15a.js:1:129459)
ye @ main-53e4c75c03e21105f4ea.js:1
main-53e4c75c03e21105f4ea.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
ye @ main-53e4c75c03e21105f4ea.js:1
main-53e4c75c03e21105f4ea.js:1 Error rendering page:  TypeError: Cannot read property 'cookies' of undefined
    at m (_app-6dad4b8429480d2cb5ca.js:1)
    at _app-6dad4b8429480d2cb5ca.js:1
    at l (main-53e4c75c03e21105f4ea.js:1)
    at Generator._invoke (main-53e4c75c03e21105f4ea.js:1)
    at Generator.next (main-53e4c75c03e21105f4ea.js:1)
    at a (_app-6dad4b8429480d2cb5ca.js:1)
    at c (_app-6dad4b8429480d2cb5ca.js:1)
(anonymous) @ main-53e4c75c03e21105f4ea.js:1

**Comment by vinyldarkscratch** [comment]
This seems like a request for development help.  Please use something like StackOverflow to post your question; this repository is not a help forum.
