### ISSUE TITLE
npm test issues - spec_url data

### ISSUE THREAD

**Issue by rebloor** [mdn/browser-compat-data#12790]
Getting this failure when executing `npm test`

```
1) spec_url data
       spec_urls only use allow listed hosts by w3c/browser-specs (and our exception list):

      AssertionError [ERR_ASSERTION]: Invalid specification host(s) found. Try a more current specification URL and/or
      check if the specification URL is listed in https://github.com/w3c/browser-specs.
      + expected - actual

      -[
      -  "https://wicg.github.io/urlpattern/#urlpattern"
      -  "https://wicg.github.io/urlpattern/#dom-urlpattern-urlpattern"
      -  "https://wicg.github.io/urlpattern/#dom-urlpattern-exec"
      -  "https://wicg.github.io/urlpattern/#dom-urlpattern-hash"
      -  "https://wicg.github.io/urlpattern/#dom-urlpattern-hostname"
      -  "https://wicg.github.io/urlpattern/#dom-urlpattern-password"
      -  "https://wicg.github.io/urlpattern/#dom-urlpattern-pathname"
      -  "https://wicg.github.io/urlpattern/#dom-urlpattern-port"
      -  "https://wicg.github.io/urlpattern/#dom-urlpattern-protocol"
      -  "https://wicg.github.io/urlpattern/#dom-urlpattern-search"
      -  "https://wicg.github.io/urlpattern/#dom-urlpattern-test"
      -  "https://wicg.github.io/urlpattern/#dom-urlpattern-username"
      -  "https://tc39.es/proposal-intl-enumeration/#sec-intl.supportedvaluesof"
      -]
      +[]
      
      at Context.<anonymous> (test/spec-urls.test.js:64:12)
      at processImmediate (internal/timers.js:464:21)
```

**Comment by rebloor** [comment]
Thank you @queengooborg, that fixed the issue
