### ISSUE TITLE
PROBLEM ERROR ENOENT 

### ISSUE THREAD

**Issue by GKans** [mdn/browser-compat-data#14875]
C:\Users\pc\Desktop\Νέος φάκελος\Generative_Gif_Engine-main\src\config.js
(node:5008) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\pc\Desktop\Νέος φάκελος\Generative_Gif_Engine-main\node_modules\canvas\lib\image.js:91
  SetSource.call(img, src);
            ^

Error: ENOENT, No such file or directory 'undefined'
    at setSource (C:\Users\pc\Desktop\Νέος φάκελος\Generative_Gif_Engine-main\node_modules\canvas\lib\image.js:91:13)
    at Image.set (C:\Users\pc\Desktop\Νέος φάκελος\Generative_Gif_Engine-main\node_modules\canvas\lib\image.js:62:9)
    at C:\Users\pc\Desktop\Νέος φάκελος\Generative_Gif_Engine-main\node_modules\canvas\index.js:34:15
    at new Promise (<anonymous>)
    at loadImage (C:\Users\pc\Desktop\Νέος φάκελος\Generative_Gif_Engine-main\node_modules\canvas\index.js:23:10)
    at C:\Users\pc\Desktop\Νέος φάκελος\Generative_Gif_Engine-main\src\main.js:137:25
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\pc\Desktop\Νέος φάκελος\Generative_Gif_Engine-main\src\main.js:136:10)
    at C:\Users\pc\Desktop\Νέος φάκελος\Generative_Gif_Engine-main\src\main.js:253:31
    at Array.forEach (<anonymous>) {
  errno: 2,
  code: 'ENOENT',
  path: 'undefined',
  syscall: 'fopen'
}

**Comment by GKans** [comment]
Where is a spam label
