### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by rebloor** [mdn/browser-compat-data#16716]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

On advice, after pulling the latest have run set up using `npm install` > `npm ci` – get the same behavior in main and my own branches

```
npm test

> @mdn/browser-compat-data@5.1.1 test
> npm run format && npm run lint && npm run unittest


> @mdn/browser-compat-data@5.1.1 format
> npx eslint "**/*.ts" && npx prettier --check "**/*.md" "**/*.json"


/Users/…/Documents/repositories/…/browser-compat-data/scripts/release/build.test.ts
   6:8  warning  'bcd' is defined but never used               @typescript-eslint/no-unused-vars
   8:3  warning  'applyMirroring' is defined but never used    @typescript-eslint/no-unused-vars
   9:3  warning  'createDataBundle' is defined but never used  @typescript-eslint/no-unused-vars
  10:3  warning  'generateMeta' is defined but never used      @typescript-eslint/no-unused-vars

/Users/…/Documents/repositories/…/browser-compat-data/test/linter/test-obsolete.test.ts
  20:5  warning  '_' is defined but never used  @typescript-eslint/no-unused-vars

✖ 5 problems (0 errors, 5 warnings)

Checking formatting...
All matched files use Prettier code style!

> @mdn/browser-compat-data@5.1.1 lint
> ts-node test/lint

/Users/…/Documents/repositories/…/browser-compat-data/node_modules/ts-node/src/index.ts:843
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
test/linter/test-consistency.ts:486:13 - error TS2322: Type 'SupportStatement | undefined' is not assignable to type 'InternalSupportStatement'.
  Type 'undefined' is not assignable to type 'InternalSupportStatement'.

486         let browserData: InternalSupportStatement = compatData.support[browser];
                ~~~~~~~~~~~

    at createTSError (/Users/…/Documents/repositories/…/browser-compat-data/node_modules/ts-node/src/index.ts:843:12)
    at reportTSError (/Users/…/Documents/repositories/…/browser-compat-data/node_modules/ts-node/src/index.ts:847:19)
    at getOutput (/Users/…/Documents/repositories/…/browser-compat-data/node_modules/ts-node/src/index.ts:1057:36)
    at Object.compile (/Users/…/Documents/repositories/…/browser-compat-data/node_modules/ts-node/src/index.ts:1411:41)
    at transformSource (/Users/…/Documents/repositories/…/browser-compat-data/node_modules/ts-node/src/esm.ts:400:37)
    at /Users/…/Documents/repositories/…/browser-compat-data/node_modules/ts-node/src/esm.ts:278:53
    at async addShortCircuitFlag (/Users/…/Documents/repositories/…/browser-compat-data/node_modules/ts-node/src/esm.ts:409:15)
    at async ESMLoader.load (node:internal/modules/esm/loader:407:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:326:11) {
  diagnosticCodes: [ 2322 ]
}
```

**Comment by bershanskiy** [comment]
This is odd: I followed the exact instructions and got no errors. Specifically I ran this:
```
git clone git@github.com:mdn/browser-compat-data.git
cd browser-compat-data/
npm i
npm ci
npm test
```

**Comment by queengooborg** [comment]
This is very odd, hmm...  The CI isn't failing and I haven't gotten an error recently.  I'll try to reproduce and see what the issue is!

**Comment by queengooborg** [comment]
I'm not able to reproduce this on my end.  I've run `npm i && npm test` and have not run into any issues.  I tried with `npm ci` as well and still could not get an issue.

What version of TypeScript do you have installed?  Also, what version of Node do you have?

**Comment by rebloor** [comment]
Node is v16.15.0, for `tsc -v` I get an error.

**Comment by queengooborg** [comment]
The error on running `tsc -v` might be a part of the problem.  I'd recommend running `npm un --global typescript tsc` to see if the global installation is causing the issue?

**Comment by rebloor** [comment]
```
npm un --global typescript tsc

up to date, audited 1 package in 63ms

found 0 vulnerabilities
```

**Comment by queengooborg** [comment]
(Since this issue does seem to be a local issue rather than a project issue, I'm going to close this.  I'm happy to help diagnose this in DMs however -- feel free to ping me through Telegram/Matrix!)
