### ISSUE TITLE
Issues with Lint script

### ISSUE THREAD

**Issue by DeeprajPandey** [mdn/browser-compat-data#2387]
I'm working on the PositionError compat data and running `npm run lint` gives me this

```
> mdn-browser-compat-data@0.0.39 lint /Users/***/Documents/workingdir/browser-compat-data
> node test/lint "api/PositionError.json"

api/PositionError.json
  JSON schema – OK
  File : /Users/***/Documents/workingdir/browser-compat-data/api/PositionError.json
  Style – Error on line #2
    Actual:   	"api": {
    Expected:   "api": {
  Browser versions – OK

Problems in 1 file:
api/PositionError.json
  JSON schema – OK
  File : /Users/***/Documents/workingdir/browser-compat-data/api/PositionError.json
  Style – Error on line #2
    Actual:   	"api": {
    Expected:   "api": {
  Browser versions – OK
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdn-browser-compat-data@0.0.39 lint: `node test/lint "api/PositionError.json"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdn-browser-compat-data@0.0.39 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/***/.npm/_logs/2018-06-29T06_52_42_367Z-debug.log
```

Here's the complete log from the last line

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/***/.nvm/versions/node/v8.10.0/bin/node',
1 verbose cli   '/Users/***/.nvm/versions/node/v8.10.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'lint',
1 verbose cli   'api/PositionError.json' ]
2 info using npm@5.7.1
3 info using node@v8.10.0
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle mdn-browser-compat-data@0.0.39~prelint: mdn-browser-compat-data@0.0.39
6 info lifecycle mdn-browser-compat-data@0.0.39~lint: mdn-browser-compat-data@0.0.39
7 verbose lifecycle mdn-browser-compat-data@0.0.39~lint: unsafe-perm in lifecycle true
8 verbose lifecycle mdn-browser-compat-data@0.0.39~lint: PATH: /Users/***/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/***/Documents/workingdir/browser-compat-data/node_modules/.bin:/Users/***/.nvm/versions/node/v8.10.0/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle mdn-browser-compat-data@0.0.39~lint: CWD: /Users/***/Documents/workingdir/browser-compat-data
10 silly lifecycle mdn-browser-compat-data@0.0.39~lint: Args: [ '-c', 'node test/lint "api/PositionError.json"' ]
11 silly lifecycle mdn-browser-compat-data@0.0.39~lint: Returned: code: 1  signal: null
12 info lifecycle mdn-browser-compat-data@0.0.39~lint: Failed to exec lint script
13 verbose stack Error: mdn-browser-compat-data@0.0.39 lint: `node test/lint "api/PositionError.json"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/***/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/***/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid mdn-browser-compat-data@0.0.39
15 verbose cwd /Users/***/Documents/workingdir/browser-compat-data
16 verbose Darwin 17.6.0
17 verbose argv "/Users/***/.nvm/versions/node/v8.10.0/bin/node" "/Users/***/.nvm/versions/node/v8.10.0/bin/npm" "run" "lint" "api/PositionError.json"
18 verbose node v8.10.0
19 verbose npm  v5.7.1
20 error code ELIFECYCLE
21 error errno 1
22 error mdn-browser-compat-data@0.0.39 lint: `node test/lint "api/PositionError.json"`
22 error Exit status 1
23 error Failed at the mdn-browser-compat-data@0.0.39 lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Any idea what I am doing wrong?

**Comment by ExE-Boss** [comment]
Do you have any trailing spaces? Because it might be trailing spaces, but I can’t verify that without access to the full `api/PositionError.json` file.

**Comment by DeeprajPandey** [comment]
Here: https://github.com/DeeprajPandey/browser-compat-data/blob/add-pError/api/PositionError.json

**Comment by DeeprajPandey** [comment]
I figured it out. I was using tabs for indentation which was causing the test to fail. When I converted all the tabs to spaces, lint passed.
Is there any specific reason this check is in place?

**Comment by ExE-Boss** [comment]
Ask @Elchi3 or one of the other repository maintainers.

**Comment by Elchi3** [comment]
Consistent formatting helps us with mass-changes to the data (e.g. programmatically updating many files for support data changes or structural data changes). If the formatting is random, diffs become harder to read.

**Comment by DeeprajPandey** [comment]
Yeah, I understood that, thanks @Elchi3. What I wanted to ask is if there was any specific reason behind keeping it spaces only or it was just one of the two?

**Comment by Elchi3** [comment]
Just choosing one of the two.
